name: Calculadora
on:
    push:
jobs:
    testes:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: configurar o java
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '24'
            - name: executar os testes
              run: mvn test